### ISSUE TITLE
Database setup problem

### ISSUE THREAD

**Issue by jasonfharris** [DandyDev/graphite-statsd-ansible-vagrant#1]
Hi, I am trying to get this running on a digital ocean droplet using debian wheezy.

(I changed the starting script so it runs from root, i.e. in graphite.yml I changed
   sudo: True
to
  remote_user: root

The roles run fine until the postgres setup when it errors out with the following:
TASK: [postgres | setup database] ********************************************* 
<silverams.mydomain.com> ESTABLISH CONNECTION FOR USER: root
<silverams.mydomain.com> REMOTE_MODULE postgresql_db template=template0 state=present lc_ctype=en_US.UTF-8 db=graphite lc_collate=en_US.UTF-8 encoding=UTF-8
<silverams.mydomain.com> EXEC ['ssh', '-C', '-tt', '-vvv', '-o', 'ControlMaster=auto', '-o', 'ControlPersist=60s', '-o', 'ControlPath=/Users/jason/.ansible/cp/ansible-ssh-%h-%p-%r', '-o', 'KbdInteractiveAuthentication=no', '-o', 'PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey', '-o', 'PasswordAuthentication=no', '-o', 'User=root', '-o', 'ConnectTimeout=10', 'silverams.mydomain.com', "/bin/sh -c 'mkdir -p $HOME/.ansible/tmp/ansible-tmp-1402836147.79-248339011717841 && echo $HOME/.ansible/tmp/ansible-tmp-1402836147.79-248339011717841'"]
<silverams.mydomain.com> PUT /var/folders/rk/7chm_bwd7tx2dsbj30h1gsgh0000gn/T/tmpBDXyeq TO /root/.ansible/tmp/ansible-tmp-1402836147.79-248339011717841/postgresql_db
<silverams.mydomain.com> EXEC ['ssh', '-C', '-tt', '-vvv', '-o', 'ControlMaster=auto', '-o', 'ControlPersist=60s', '-o', 'ControlPath=/Users/jason/.ansible/cp/ansible-ssh-%h-%p-%r', '-o', 'KbdInteractiveAuthentication=no', '-o', 'PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey', '-o', 'PasswordAuthentication=no', '-o', 'User=root', '-o', 'ConnectTimeout=10', 'silverams.mydomain.com', u"/bin/sh -c 'LC_CTYPE=en_US.UTF-8 LANG=en_US.UTF-8 /usr/bin/python /root/.ansible/tmp/ansible-tmp-1402836147.79-248339011717841/postgresql_db; rm -rf /root/.ansible/tmp/ansible-tmp-1402836147.79-248339011717841/ >/dev/null 2>&1'"]
failed: [silverams.mydomain.com] => {"failed": true, "item": ""}
msg: unable to connect to database: FATAL:  Peer authentication failed for user "postgres"

Any advice?

Thanks!
   Jason

**Comment by DandyDev** [comment]
Sorry I haven't gotten back on this. Are you still having problems with this @jasonfharris ?
