### ISSUE TITLE
How to access this?

### ISSUE THREAD

**Issue by iamdustan** [DandyDev/graphite-statsd-ansible-vagrant#3]
Hey @DandyDev,

My question is most likely due to me not being a devops person _at all_ and never using graphite, statsd, or ansible before. Once this is up and running (I believe I’m at this point) how do I access the graphite webview and post data to statsd?

I’ve tried accessing `http://192.168.33.20/` (referenced in the Vagrantfile) and `graphite.local` (although I’ve done nothing to my `hosts` file to reference that).

**Comment by vohof** [comment]
@DandyDev Hi, what's the username and password for the web interface?

**Comment by DandyDev** [comment]
@vohof have a look at [the README](https://github.com/DandyDev/graphite-statsd-ansible-vagrant#superuser). There is says that you need to create a superuser first :)

**Comment by vohof** [comment]
@DandyDev Shooot, sorry!
