### ISSUE TITLE
Ansible hangs on [nodejs | make]

### ISSUE THREAD

**Issue by mattLummus** [DandyDev/graphite-statsd-ansible-vagrant#6]
![screen shot 2015-04-02 at 12 04 13 pm](https://cloud.githubusercontent.com/assets/6342564/6968959/7ca86e90-d930-11e4-8d12-23e4ddb855f7.png)

I imagine it may related to this? https://github.com/ansible/ansible/issues/3881

**Comment by mattLummus** [comment]
As is often the case, as soon as I report the issue it fixes itself. Third try was the charm. Closing this issue :)

**Comment by DandyDev** [comment]
NodeJS compilation sadly takes a really really long time :)
