### ISSUE TITLE
Graphite fails to install under vagrant

### ISSUE THREAD

**Issue by markpitchless** [DandyDev/graphite-statsd-ansible-vagrant#9]
Get the following error when trying to provision (vagrant up):

```
TASK: [graphite | graphite conf] ********************************************** 
failed: [statserver] => {"failed": true}
msg: Destination directory /opt/graphite/webapp/graphite does not exist
```

Tried setting the graphite version to 0.9.x instead of master but get the same error. Also seeing the same error on statsserver.

```
Oracle VM VirtualBox Manager 4.3.28
> lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 14.10
Release:    14.10
Codename:   utopic
> ansible --version
ansible 1.9.1
  configured module search path = None
> vagrant --version
Vagrant 1.7.2
```

**Comment by rosswilson** [comment]
I'm also seeing this same error. I'm starting to investigate why it's happening right now.

**Comment by dabutcher** [comment]
I'm having same issue after ansible runs it fails at TASK: [graphite | graphite conf]... directory ...does not exist

Cloned master today with default settings, has anyone figured this out yet?

**Comment by bosgood** [comment]
Add this before the line that breaks:

```
- name: ensure graphite conf directory exists
  file:
    path: /opt/graphite/webapp/graphite
    state: directory
```

**Comment by pgilad** [comment]
Yep that solves it @bosgood

**Comment by erikahend** [comment]
Also under roles/graphite/tasks/main.yml the graphite settings may not work if graphite doesn't have an __init__.py file. The file could be modified like this:

- name: create init file for python
  shell: touch /opt/graphite/webapp/graphite/__init__.py; chmod 644 /opt/graphite/webapp/graphite/__init__.py

- name: syncdb for graphite
  shell: export PYTHONPATH=/opt/graphite/webapp/; /opt/graphite/bin/python /opt/graphite/bin/django-admin.py syncdb --noinput --settings=graphite.local_settings

**Comment by DandyDev** [comment]
Fixed in https://github.com/DandyDev/graphite-statsd-ansible-vagrant/commit/ae6e7d28a8051eeca08cd7d16112712f35475273
